export default function Head() {
  return (
    <>
      <title>PIAIC DEMO SITE</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/PIAIC_LOGO.svg' />
    </>
  )
}
